sonar.organization=huybroxx
sonar.projectKey=Huybroxx_final-cicd-fpt-HuyNN69
sonar.projectName=FastAPI DevOps Service
sonar.projectVersion=1.0.0

sonar.sources=backend/app
sonar.tests=backend/tests

sonar.language=py
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.python.xunit.reportPath=backend/test-results.xml

sonar.exclusions=**/__pycache__/**,**/.venv/**,**/tests/**,**/nginx/**,**/scripts/**

sonar.qualitygate.wait=true